### PR TITLE
Fix Interactive Session state tracking

### LINKED ISSUE #1061: Lighter sessions always display session states as IDLE state even during active query execution
Lighter sessions show an IDLE state even while queries are running, though the expectation was to see BUSY during execution and IDLE when not executing.

Additionally, in lighter batches, I see the following states: NOT_STARTED, STARTING, IDLE, BUSY, SHUTTING_DOWN, ERROR, DEAD, KILLED, and SUCCESS. 
I only see a few of these states being applied to sessions, such as NOT_STARTED (when the session is about to start), STARTING (when the session has started), IDLE (where it remains most of the time, both during execution and when not executing), and ERROR. I would like to know if all these states are supposed to apply to sessions as well.

Screenshot 2024-06-18 at 2 57 07 PM

### PR DESCRIPTION
**Pull request by pdambrauskas**
Fixes #1061

@Minutis

### CODE REVIEW

File: server/src/main/java/com/exacaster/lighter/application/sessions/processors/python/PythonSessionIntegration.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ public void runServer(StartupEvent event) {
 
     @Override
     public boolean hasWaitingStatement(Application application) {
-        var waitingStatements = statementStorage.findByState(application.getAppId(), "waiting");
```
Comment (pdambrauskas) [inline server/src/main/java/com/exacaster/lighter/application/sessions/processors/python/PythonSessionIntegration.java:98]: Basically this was the root cause.
Other changes are refactoring - decoupling status tracker from sessions layer.

**Review by Minutis — APPROVED** [review]
